package com.szkct.weloopbtsmartdevice.data.greendao.dao;

import android.database.sqlite.SQLiteDatabase;

import com.szkct.weloopbtsmartdevice.data.WatchInfoData;
import com.szkct.weloopbtsmartdevice.data.greendao.AlarmClockData;
import com.szkct.weloopbtsmartdevice.data.greendao.Bloodpressure;
import com.szkct.weloopbtsmartdevice.data.greendao.Customer;
import com.szkct.weloopbtsmartdevice.data.greendao.Ecg;
import com.szkct.weloopbtsmartdevice.data.greendao.GpsPointData;
import com.szkct.weloopbtsmartdevice.data.greendao.GpsPointDetailData;
import com.szkct.weloopbtsmartdevice.data.greendao.HearData;
import com.szkct.weloopbtsmartdevice.data.greendao.Order;
import com.szkct.weloopbtsmartdevice.data.greendao.Oxygen;
import com.szkct.weloopbtsmartdevice.data.greendao.RunData;
import com.szkct.weloopbtsmartdevice.data.greendao.SleepData;
import com.szkct.weloopbtsmartdevice.data.greendao.Temperature;

import java.util.Map;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.AbstractDaoSession;
import de.greenrobot.dao.identityscope.IdentityScopeType;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 *
 * @see de.greenrobot.dao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig runDataDaoConfig;
    private final DaoConfig sleepDataDaoConfig;
    private final DaoConfig hearDataDaoConfig;
    private final DaoConfig customerDaoConfig;
    private final DaoConfig orderDaoConfig;
    private final DaoConfig GpsPointDaoConfig;
    private final DaoConfig GpsPointDetailDaoConfig;
    private final DaoConfig alarmClockDetailDaoConfig;
    private final DaoConfig bloodpressureDaosConfig;
    private final DaoConfig oxygenDaoConfig;
    private final DaoConfig ecgDaoConfig;
    private final DaoConfig temperatureDaoConfig;
    private final DaoConfig watchInfoConfig;




    private final RunDataDao runDataDao;
    private final SleepDataDao sleepDataDao;
    private final HearDataDao hearDataDao;
    private final CustomerDao customerDao;
    private final OrderDao orderDao;
    private final GpsPointDao mGpsPointDao;
    private final GpsPointDetailDao mGpsPointDetailDao;
    private final AlarmClockDataDao alarmClockDataDao;
    private final BloodpressureDao bloodpressureDaos;
    private OxyDao oxygenDao;
    private EcgDao ecgDao;
    private TemperatureDao temperatureDao;
    private final WatchInfoDataDao watchInfoDataDao;




    public DaoSession(SQLiteDatabase db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        runDataDaoConfig = daoConfigMap.get(RunDataDao.class).clone();
        runDataDaoConfig.initIdentityScope(type);

        sleepDataDaoConfig = daoConfigMap.get(SleepDataDao.class).clone();
        sleepDataDaoConfig.initIdentityScope(type);

        hearDataDaoConfig = daoConfigMap.get(HearDataDao.class).clone();
        hearDataDaoConfig.initIdentityScope(type);

        customerDaoConfig = daoConfigMap.get(CustomerDao.class).clone();
        customerDaoConfig.initIdentityScope(type);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        GpsPointDaoConfig = daoConfigMap.get(GpsPointDao.class).clone();
        GpsPointDaoConfig.initIdentityScope(type);

        GpsPointDetailDaoConfig = daoConfigMap.get(GpsPointDetailDao.class).clone();
        GpsPointDetailDaoConfig.initIdentityScope(type);

        alarmClockDetailDaoConfig = daoConfigMap.get(AlarmClockDataDao.class).clone();
        alarmClockDetailDaoConfig.initIdentityScope(type);

        bloodpressureDaosConfig = daoConfigMap.get(BloodpressureDao.class).clone();
        bloodpressureDaosConfig.initIdentityScope(type);

        oxygenDaoConfig = daoConfigMap.get(OxyDao.class).clone();
        oxygenDaoConfig.initIdentityScope(type);

        ecgDaoConfig = daoConfigMap.get(EcgDao.class).clone();
        ecgDaoConfig.initIdentityScope(type);

        temperatureDaoConfig = daoConfigMap.get(TemperatureDao.class).clone();
        temperatureDaoConfig.initIdentityScope(type);

        watchInfoConfig = daoConfigMap.get(WatchInfoDataDao.class).clone();
        watchInfoConfig.initIdentityScope(type);

        runDataDao = new RunDataDao(runDataDaoConfig, this);
        sleepDataDao = new SleepDataDao(sleepDataDaoConfig, this);
        hearDataDao = new HearDataDao(hearDataDaoConfig, this);
        customerDao = new CustomerDao(customerDaoConfig, this);
        orderDao = new OrderDao(orderDaoConfig, this);
        mGpsPointDao = new GpsPointDao(GpsPointDaoConfig, this);
        mGpsPointDetailDao = new GpsPointDetailDao(GpsPointDetailDaoConfig, this);
        alarmClockDataDao = new AlarmClockDataDao(alarmClockDetailDaoConfig,this);
        bloodpressureDaos = new BloodpressureDao(bloodpressureDaosConfig,this);
        oxygenDao= new OxyDao(oxygenDaoConfig,this);
        ecgDao= new EcgDao(ecgDaoConfig,this);
        temperatureDao= new TemperatureDao(temperatureDaoConfig,this);
        watchInfoDataDao = new WatchInfoDataDao(watchInfoConfig,this);

        registerDao(RunData.class, runDataDao);
        registerDao(SleepData.class, sleepDataDao);
        registerDao(HearData.class, hearDataDao);
        registerDao(Customer.class, customerDao);
        registerDao(Order.class, orderDao);
        registerDao(GpsPointData.class, mGpsPointDao);
        registerDao(GpsPointDetailData.class, mGpsPointDetailDao);
        registerDao(AlarmClockData.class, alarmClockDataDao);
        registerDao(Bloodpressure.class, bloodpressureDaos);
        registerDao(Oxygen.class, oxygenDao);
        registerDao(Ecg.class, ecgDao);
        registerDao(Temperature.class, temperatureDao);
        registerDao(WatchInfoData.class,watchInfoDataDao);
    }

    public void clear() {
        runDataDaoConfig.getIdentityScope().clear();
        sleepDataDaoConfig.getIdentityScope().clear();
        hearDataDaoConfig.getIdentityScope().clear();
        customerDaoConfig.getIdentityScope().clear();
        orderDaoConfig.getIdentityScope().clear();
        GpsPointDaoConfig.getIdentityScope().clear();
        GpsPointDetailDaoConfig.getIdentityScope().clear();
        alarmClockDetailDaoConfig.getIdentityScope().clear();
        bloodpressureDaosConfig.getIdentityScope().clear();
        oxygenDaoConfig.getIdentityScope().clear();
        ecgDaoConfig.getIdentityScope().clear();
        temperatureDaoConfig.getIdentityScope().clear();
        watchInfoConfig.getIdentityScope().clear();
    }

    public RunDataDao getRunDataDao() {
        return runDataDao;
    }

    public SleepDataDao getSleepDataDao() {
        return sleepDataDao;
    }

    public HearDataDao getHearDataDao() {
        return hearDataDao;
    }

    public CustomerDao getCustomerDao() {
        return customerDao;
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public GpsPointDetailDao getGpsPointDetailDao() {return mGpsPointDetailDao;}

    public GpsPointDao getGpsPointDao() {
        return mGpsPointDao;
    }

    public AlarmClockDataDao getAlarmClockDataDao() { return alarmClockDataDao;}

    public BloodpressureDao getBloodpressureDaos() {return bloodpressureDaos;}

    public OxyDao getOxygenDao() {return oxygenDao;}

    public EcgDao getEcgDao() {
        return ecgDao;
    }

    public TemperatureDao getTemperatureDao() {
        return temperatureDao;
    }

    public WatchInfoDataDao getWatchInfoDataDao(){return watchInfoDataDao;}
}
