package com.szkct.weloopbtsmartdevice.data.greendao.dao;

import android.database.Cursor;
import android.database.sqlite.SQLiteDatabase;
import android.database.sqlite.SQLiteStatement;

import com.szkct.weloopbtsmartdevice.data.greendao.Oxygen;

import de.greenrobot.dao.AbstractDao;
import de.greenrobot.dao.Property;
import de.greenrobot.dao.internal.DaoConfig;


// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * DAO for table HEART.
*/
public class OxyDao extends AbstractDao<Oxygen, Long> {

    public static final String TABLENAME = "Oxygen_test";    // 睡眠表
    /**
     * Properties of entity HearData.<br/>
     * Can be used for QueryBuilder and for referencing column names.
    */
    public static class Properties {
        public final static Property Id = new Property(0, Long.class, "id", true, "_id");
        public final static Property Mac = new Property(1, String.class, "mac", false, "Mac");
        public final static Property Date = new Property(2, String.class, "date", false, "Data");
        public final static Property Hour = new Property(3, String.class, "hour", false, "Hour");
        public final static Property MinOxygen = new Property(4, String.class, "minOxygen", false, "MinOxygen");
        public final static Property HeightOxygen = new Property(5, String.class, "heightOxygen", false, "HeightOxygen");
        public final static Property Oxygen = new Property(6, String.class, "oxygen", false, "Oxygen");

    };


    public OxyDao(DaoConfig config) {
        super(config);
    }

    public OxyDao(DaoConfig config, DaoSession daoSession) {
        super(config, daoSession);
    }

    /** Creates the underlying database table. */
    public static void createTable(SQLiteDatabase db, boolean ifNotExists) {
        String constraint = ifNotExists? "IF NOT EXISTS ": "";
        db.execSQL("CREATE TABLE " + constraint + "'Oxygen_test' (" + //
                "'_id' INTEGER PRIMARY KEY ," + // 0: id
                "'Mac' TEXT NOT NULL ," + // 1: HeightBlood
                "'Data' TEXT NOT NULL ," + // 2: MinBlood
                "'Hour' TEXT NOT NULL ," + // 3: Hour
                "'MinOxygen' TEXT NOT NULL ," + // 4: Date
                "'HeightOxygen' TEXT NOT NULL ," + // 5: Mac
                "'Oxygen' TEXT NOT NULL);" // 5: Conunt
                ); // 12

    }

    /** Drops the underlying database table. */
    public static void dropTable(SQLiteDatabase db, boolean ifExists) {
        String sql = "DROP TABLE " + (ifExists ? "IF EXISTS " : "") + "'Oxygen_test'";
        db.execSQL(sql);
    }

    /** @inheritdoc */
    @Override
    protected void bindValues(SQLiteStatement stmt, Oxygen entity) {
        stmt.clearBindings();
 
        Long id = entity.getId();
        if (id != null) {
            stmt.bindLong(1, id);
        }
        stmt.bindString(2, entity.getMac());
        stmt.bindString(3, entity.getData());
        stmt.bindString(4, entity.getHour());
        stmt.bindString(5, entity.getMinOxygen());
        stmt.bindString(6, entity.getHeightOxygen());
        stmt.bindString(7, entity.getOxygen());

    }

    /** @inheritdoc */
    @Override
    public Long readKey(Cursor cursor, int offset) {
        return cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0);
    }    

    /** @inheritdoc */
    @Override
    public Oxygen readEntity(Cursor cursor, int offset) {
        Oxygen entity = new Oxygen(
            cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0), // id
            cursor.getString(offset + 1), // HeightBlood
            cursor.getString(offset + 2), // MinBlood
            cursor.getString(offset + 3), // Hour
            cursor.getString(offset + 4), // Date
            cursor.getString(offset + 5) ,// Mac
            cursor.getString(offset + 6) // Mac

        );
        return entity;
    }
     
    /** @inheritdoc */
    @Override
    public void readEntity(Cursor cursor, Oxygen entity, int offset) {
        entity.setId(cursor.isNull(offset + 0) ? null : cursor.getLong(offset + 0));
        entity.setMac(cursor.getString(offset + 1));
        entity.setData(cursor.getString(offset + 2));
        entity.setHour(cursor.getString(offset + 3));
        entity.setMinOxygen(cursor.getString(offset + 4));
        entity.setHeightOxygen(cursor.getString(offset + 5));
        entity.setOxygen(cursor.getString(offset + 6));

     }
    
    /** @inheritdoc */
    @Override
    protected Long updateKeyAfterInsert(Oxygen entity, long rowId) {
        entity.setId(rowId);
        return rowId;
    }
    
    /** @inheritdoc */
    @Override
    public Long getKey(Oxygen entity) {
        if(entity != null) {
            return entity.getId();
        } else {
            return null;
        }
    }

    /** @inheritdoc */
    @Override    
    protected boolean isEntityUpdateable() {
        return true;
    }
    
}
