package com.szkct.weloopbtsmartdevice.data.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

import static com.kct.fundo.btnotification.R.string.calorie;
import static com.kct.fundo.btnotification.R.string.date;
import static com.kct.fundo.btnotification.R.string.distance;
import static com.kct.fundo.btnotification.R.string.hour;

/**
 * Entity mapped to table ALARMCLOCK.
 */
public class AlarmClockData implements Serializable {

    private Long id;
    /** Not-null value. */
    private String mac;
    /** Not-null value. */
    private String mid;
    /** Not-null value. */
    private String upload;
    /** Not-null value. */
    private String time;    //闹钟时间
    /** Not-null value. */
    private String type;       //开启/关闭
    /** Not-null value. */
    private String cycle;      //重复设置
    /** Not-null value. */
    private String alarm_time;  //闹钟当前时间
    /** Not-null value. */
    private String remind;      //提醒模式

    public AlarmClockData() {
    }

    public AlarmClockData(Long id) {
        this.id = id;
    }

    public AlarmClockData(Long id, String mac, String mid, String upload, String time, String type, String cycle, String alarm_time, String remind) {
        this.id = id;
        this.mac = mac;
        this.mid = mid;
        this.upload = upload;
        this.time = time;
        this.type = type;
        this.cycle = cycle;
        this.alarm_time = alarm_time;
        this.remind = remind;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMac() {
        return mac;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /** Not-null value. */
    public String getMid() {
        return mid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /** Not-null value. */
    public String getUpload() {
        return upload;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpload(String upload) {
        this.upload = upload;
    }

    /** Not-null value. */
    public String getTime() {
        return time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTime(String time) {
        this.time = time;
    }

    /** Not-null value. */
    public String getType() {
        return type;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setType(String type) {
        this.type = type;
    }

    /** Not-null value. */
    public String getCycle() {
        return cycle;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCycle(String cycle) {
        this.cycle = cycle;
    }

    /** Not-null value. */
    public String getAlarm_time() {
        return alarm_time;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setAlarm_time(String alarm_time) {
        this.alarm_time = alarm_time;
    }

    /** Not-null value. */
    public String getRemind() {
        return remind;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setRemind(String remind) {
        this.remind = remind;
    }

	@Override
	public String toString() {
		return "RunData [id=" + id + ", mac=" + mac + ", mid=" + mid
				+ ", upload=" + upload + ", time=" + time + ", type="
				+ type + ", cycle=" + cycle + ", alarm_time=" + alarm_time + ", remind="
				+ remind + "]";
	}
    

}
