package com.szkct.weloopbtsmartdevice.data.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import java.io.Serializable;

/**
 * Entity mapped to table HEART.
 */
public class GpsPointDetailData implements Serializable {   // 基础数据

    private static final long serialVersionUID = 4598910917081132372L;

    private Long id;
    /**
     * Not-null value.
     */
    private String mac;
    /**
     * Not-null value.
     */
    private String mid;
//    /**
//     * 运动实时 经纬度用于详情界面
//     */
//    private String lat;
//    /**
//     * 运动实时 经纬度用于详情界面
//     */
//    private String lon;
    /**
     * 距离
     */
    private double mile;
    /**
     * 海拔
     */
    private String altitude;
    /**
     * 日期
     */
    private String date;
    /**
     * 每KM的配速
     */
    private String speed;  // TODO 速度
    /**
     * 运动时间 时分秒
     */
    private String sportTime;
    /**
     * 卡里路
     */
    private String calorie;
    /**
     * 运动时间秒数
     */
    private String sTime;
//    /**
//     * 运动实时距离  （暂无用）
//     */
//    private String distance;
    /**
     * 每10米的维度
     */
    private String arrLat;
    /**
     * 每10米的经度
     **/
    private String arrLng;
    /**
     * 运动实时配速
     */
    private String mCurrentSpeed;
    /**
     * 运动实时总时间 总距离 配速  每10米的配速
     */
    private String arrTotalSpeed;
    /**
     *时间戳
     */
    private String timeMillis;
    /**
     *运动类型
     */
    private String sportType;
    /**
     *心率
     */
    private String  heartRate;
    /**
     *手机 手表数据区分字段 1.表示手机 2.手表
     */
    private String  deviceType;    // 设备类型    2：手表   1： 手机
    /**
     *暂停次数记录
     */
    private String pauseNumber;
    /**
     *暂停时间记录
     */
    private String  pauseTime;

    /**
     *速度数组。用于画图
     */
    private String  arrspeed;
    /**
     *步频数组。用于画图
     *
     */
    private String  arrcadence;
    /**
     *海拔数组。用于画图
     */
    private String  arraltitude;

    /**
     *心率数组。用于画图
     */
    private String  arrheartRate;

    /**
     *步幅
     */
    private String  min_step_width;
    private String  max_step_width;
    private String  ave_step_width;

    private String  step;

    public String getArrheartRate() {
        return arrheartRate;
    }

    public void setArrheartRate(String arrheartRate) {
        this.arrheartRate = arrheartRate;
    }

    public String getMin_step_width() {
        return min_step_width;
    }

    public void setMin_step_width(String min_step_width) {
        this.min_step_width = min_step_width;
    }

    public String getMax_step_width() {
        return max_step_width;
    }

    public void setMax_step_width(String max_step_width) {
        this.max_step_width = max_step_width;
    }

    public String getAve_step_width() {
        return ave_step_width;
    }

    public void setAve_step_width(String ave_step_width) {
        this.ave_step_width = ave_step_width;
    }

    public String getPauseNumber() {
        return pauseNumber;
    }

    public void setPauseNumber(String pauseNumber) {
        this.pauseNumber = pauseNumber;
    }

    public String getPauseTime() {
        return pauseTime;
    }

    public void setPauseTime(String pauseTime) {
        this.pauseTime = pauseTime;
    }

    public String getDeviceType() {
        return deviceType;
    }

    public void setDeviceType(String deviceType) {
        this.deviceType = deviceType;
    }

    public String getHeartRate() {
        return heartRate;
    }

    public void setHeartRate(String heartRate) {
        this.heartRate = heartRate;
    }


    public String getTimeMillis() {

        return timeMillis;
    }

    public void setTimeMillis(String timeMillis) {

        this.timeMillis = timeMillis;
    }

    public String getArrspeed() {
        return arrspeed;
    }

    public void setArrspeed(String arrspeed) {
        this.arrspeed = arrspeed;
    }

    public String getArrcadence() {
        return arrcadence;
    }

    public void setArrcadence(String arrcadence) {
        this.arrcadence = arrcadence;
    }

    public String getArraltitude() {
        return arraltitude;
    }

    public void setArraltitude(String arraltitude) {
        this.arraltitude = arraltitude;
    }

    public String getSportType() {
        return sportType;
    }

    public void setSportType(String sportType) {
        this.sportType = sportType;
    }

    public String getArrLat() {
        return arrLat;
    }

    public void setArrLat(String arrLat) {
        this.arrLat = arrLat;
    }

    public String getArrLng() {
        return arrLng;
    }

    public void setArrLng(String arrLng) {
        this.arrLng = arrLng;
    }

    public String getmCurrentSpeed() {
        return mCurrentSpeed;
    }

    public void setmCurrentSpeed(String mCurrentSpeed) {
        this.mCurrentSpeed = mCurrentSpeed;
    }

    public String getArrTotalSpeed() {
        return arrTotalSpeed;
    }

    public void setArrTotalSpeed(String arrTotalSpeed) {
        this.arrTotalSpeed = arrTotalSpeed;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    public String getMac() {
        return mac;
    }

    public void setMac(String mac) {
        this.mac = mac;
    }

    public String getMid() {
        return mid;
    }

    public void setMid(String mid) {
        this.mid = mid;
    }


    public double getMile() {
        return mile;
    }

    public void setMile(double mile) {
        this.mile = mile;
    }

    public String getAltitude() {
        return altitude;
    }

    public void setAltitude(String altitude) {
        this.altitude = altitude;
    }

    public String getDate() {
        return date;
    }

    public void setDate(String date) {
        this.date = date;
    }

    public String getSpeed() {
        return speed;
    }

    public void setSpeed(String speed) {
        this.speed = speed;
    }

    public String getSportTime() {
        return sportTime;
    }

    public void setSportTime(String sportTime) {
        this.sportTime = sportTime;
    }

    public String getCalorie() {
        return calorie;
    }

    public void setCalorie(String calorie) {
        this.calorie = calorie;
    }

    public String getsTime() {
        return sTime;
    }

    public void setsTime(String sTime) {
        this.sTime = sTime;
    }

    public String getStep() {
        return step;
    }

    public void setStep(String step) {
        this.step = step;
    }

    public GpsPointDetailData() {
    }

    public GpsPointDetailData(Long id) {
        this.id = id;
    }

    @Override
    public String toString() {
        return "GpsPointDetailData{" +
                "id=" + id +
                ", mac='" + mac + '\'' +
                ", mid='" + mid + '\'' +
                ", mile=" + mile +
                ", altitude='" + altitude + '\'' +
                ", date='" + date + '\'' +
                ", speed='" + speed + '\'' +
                ", sportTime='" + sportTime + '\'' +
                ", calorie='" + calorie + '\'' +
                ", sTime='" + sTime + '\'' +
                ", arrLat='" + arrLat + '\'' +
                ", arrLng='" + arrLng + '\'' +
                ", mCurrentSpeed='" + mCurrentSpeed + '\'' +
                ", arrTotalSpeed='" + arrTotalSpeed + '\'' +
                ", timeMillis='" + timeMillis + '\'' +
                ", sportType='" + sportType + '\'' +
                ", heartRate='" + heartRate + '\'' +
                ", deviceType='" + deviceType + '\'' +
                ", pauseNumber='" + pauseNumber + '\'' +
                ", pauseTime='" + pauseTime + '\'' +
                ", arrspeed='" + arrspeed + '\'' +
                ", arrcadence='" + arrcadence + '\'' +
                ", arraltitude='" + arraltitude + '\'' +
                ", arrheartRate='" + arrheartRate + '\'' +
                ", min_step_width='" + min_step_width + '\'' +
                ", max_step_width='" + max_step_width + '\'' +
                ", ave_step_width='" + ave_step_width + '\'' +
                ", step='" + step + '\'' +
                '}';
    }

    public GpsPointDetailData(Long id, String mac, String mid, double mile, String altitude,
                              String date, String speed, String sportTime, String calorie, String sTime,
                              String arrLat, String arrLng, String mCurrentSpeed, String arrTotalSpeed,String timeMillis,
                              String sportType,String heartRate,String deviceType,String pauseNumber,String pauseTime
            , String arrspeed, String arrcadence, String arraltitude,
                              String arrheartRate, String min_step_width, String max_step_width, String ave_step_width,String step) {
        this.id = id;
        this.mac = mac;
        this.mid = mid;
        this.mile = mile;
        this.altitude = altitude;
        this.date = date;
        this.speed = speed;
        this.sportTime = sportTime;
        this.calorie = calorie;
        this.sTime = sTime;
        this.arrLat = arrLat;
        this.arrLng = arrLng;
        this.mCurrentSpeed = mCurrentSpeed;
        this.arrTotalSpeed = arrTotalSpeed;
        this.timeMillis = timeMillis;
        this.sportType = sportType;
        this.heartRate = heartRate;
        this.deviceType = deviceType;
        this.pauseNumber = pauseNumber;
        this.pauseTime = pauseTime;
        this.arrspeed = arrspeed;
        this.arrcadence = arrcadence;
        this.arraltitude = arraltitude;
        this.arrheartRate = arrheartRate;
        this.min_step_width = min_step_width;
        this.max_step_width = max_step_width;
        this.ave_step_width = ave_step_width;
        this.step = step;
    }

    public GpsPointDetailData(String mac, String mid,double mile, String altitude,
                              String date, String speed, String sportTime, String calorie, String sTime
            , String arrLat, String arrLng, String mCurrentSpeed, String arrTotalSpeed,String timeMillis,
                              String sportType,String heartRate,String deviceType,String pauseNumber,String pauseTime
            , String arrspeed, String arrcadence, String arraltitude,
                              String arrheartRate, String min_step_width, String max_step_width, String ave_step_width,String step) {
        this.mac = mac;
        this.mid = mid;
        this.mile = mile;
        this.altitude = altitude;
        this.date = date;

        this.speed = speed;   //TODO ---  每千米的配速
        this.sportTime = sportTime;
        this.calorie = calorie;
        this.sTime = sTime;
        this.arrLat = arrLat;

        this.arrLng = arrLng;
        this.mCurrentSpeed = mCurrentSpeed;
        this.arrTotalSpeed = arrTotalSpeed;  //  TODO--- 配速 数据
        this.timeMillis = timeMillis;
        this.sportType = sportType;
        this.heartRate = heartRate;
        this.deviceType = deviceType;
        this.pauseNumber = pauseNumber;
        this.pauseTime = pauseTime;
        this.arrspeed = arrspeed;   //TODO---  速度图表数据
        this.arrcadence = arrcadence;
        this.arraltitude = arraltitude;
        this.arrheartRate = arrheartRate;
        this.min_step_width = min_step_width;
        this.max_step_width = max_step_width;
        this.ave_step_width = ave_step_width;

        this.step = step;
    }


}
