package com.szkct.weloopbtsmartdevice.data.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table HEART.
 */
public class HearData {

    private Long id;
    /** Not-null value. */
    private String mac;
    /** Not-null value. */
    private String mid;
    /** Not-null value. */
    private String upload;
    /** Not-null value. */
    private String times;
    /** Not-null value. */
    private String binTime;
    /** Not-null value. */
    private String date;
    /** Not-null value. */
    private String hour;
    /** Not-null value. */
    private String heartbeat;
    /** Not-null value. */
    private String data;
    private String avg_hata;
    private String  higt_hata;
    private String  low_hata;

    public String getAvg_hata() {
        return avg_hata;
    }

    public void setAvg_hata(String avg_hata) {
        this.avg_hata = avg_hata;
    }

    public String getHigt_hata() {
        return higt_hata;
    }

    public void setHigt_hata(String higt_hata) {
        this.higt_hata = higt_hata;
    }

    public String getLow_hata() {
        return low_hata;
    }

    public void setLow_hata(String low_hata) {
        this.low_hata = low_hata;
    }

    public HearData() {
    }

    public HearData(Long id) {
        this.id = id;
    }

    public HearData(Long id, String mac, String mid, String upload, String times, String binTime, String date, String hour, String heartbeat, String data,String MAXHATA,String lowhata,String avghata) {
        this.id = id;
        this.mac = mac;
        this.mid = mid;
        this.upload = upload;
        this.times = times;
        this.binTime = binTime;
        this.date = date;
        this.hour = hour;
        this.heartbeat = heartbeat;
        this.data = data;
        this.higt_hata=MAXHATA;
        this. low_hata=lowhata;
        this. avg_hata=avghata;
    }

    @Override
    public String toString() {
        return "HearData{" +
                "id=" + id +
                ", mac='" + mac + '\'' +
                ", mid='" + mid + '\'' +
                ", upload='" + upload + '\'' +
                ", times='" + times + '\'' +
                ", binTime='" + binTime + '\'' +
                ", date='" + date + '\'' +
                ", hour='" + hour + '\'' +
                ", heartbeat='" + heartbeat + '\'' +
                ", data='" + data + '\'' +
                ", avg_hata=" + avg_hata +
                ", higt_hata=" + higt_hata +
                ", low_hata=" + low_hata +
                '}';
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMac() {
        return mac;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /** Not-null value. */
    public String getMid() {
        return mid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /** Not-null value. */
    public String getUpload() {
        return upload;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpload(String upload) {
        this.upload = upload;
    }

    /** Not-null value. */
    public String getTimes() {
        return times;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTimes(String times) {
        this.times = times;
    }

    /** Not-null value. */
    public String getBinTime() {
        return binTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBinTime(String binTime) {
        this.binTime = binTime;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    /** Not-null value. */
    public String getHour() {
        return hour;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHour(String hour) {
        this.hour = hour;
    }

    /** Not-null value. */
    public String getHeartbeat() {
        return heartbeat;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHeartbeat(String heartbeat) {
        this.heartbeat = heartbeat;
    }

    /** Not-null value. */
    public String getData() {
        return data;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setData(String data) {
        this.data = data;
    }

}
