package com.szkct.weloopbtsmartdevice.data.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RUN.
 */
public class RunData {

    private Long id;
    /** Not-null value. */
    private String mac;
    /** Not-null value. */
    private String mid;
    /** Not-null value. */
    private String upload;
    /** Not-null value. */
    private String times;
    /** Not-null value. */
    private String binTime;
    /** Not-null value. */
    private String date;    // 日期
    /** Not-null value. */
    private String hour;
    /** Not-null value. */
    private String step;  // 分段步数
    /** Not-null value. */
    private String dayStep; // 一天的步数
    /** Not-null value. */
    private String calorie;  //
    /** Not-null value. */
    private String distance;
    /** Not-null value. */
    private String dayCalorie;
    /** Not-null value. */
    private String dayDistance;
    /** Not-null value. */
    private String data;  // 数据 ？？？ （日期）

    public RunData() {
    }

    public RunData(Long id) {
        this.id = id;
    }

    public RunData(Long id, String mac, String mid, String upload, String times, String binTime, String date, String hour, String step, String dayStep, String calorie, String distance, String dayCalorie, String dayDistance, String data) {
        this.id = id;
        this.mac = mac;
        this.mid = mid;
        this.upload = upload;
        this.times = times;
        this.binTime = binTime;
        this.date = date;
        this.hour = hour;
        this.step = step;
        this.dayStep = dayStep;
        this.calorie = calorie;
        this.distance = distance;
        this.dayCalorie = dayCalorie;
        this.dayDistance = dayDistance;
        this.data = data;
    }

    public Long getId() {
        return id;
    }

    public void setId(Long id) {
        this.id = id;
    }

    /** Not-null value. */
    public String getMac() {
        return mac;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMac(String mac) {
        this.mac = mac;
    }

    /** Not-null value. */
    public String getMid() {
        return mid;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setMid(String mid) {
        this.mid = mid;
    }

    /** Not-null value. */
    public String getUpload() {
        return upload;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setUpload(String upload) {
        this.upload = upload;
    }

    /** Not-null value. */
    public String getTimes() {
        return times;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setTimes(String times) {
        this.times = times;
    }

    /** Not-null value. */
    public String getBinTime() {
        return binTime;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setBinTime(String binTime) {
        this.binTime = binTime;
    }

    /** Not-null value. */
    public String getDate() {
        return date;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDate(String date) {
        this.date = date;
    }

    /** Not-null value. */
    public String getHour() {
        return hour;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setHour(String hour) {
        this.hour = hour;
    }

    /** Not-null value. */
    public String getStep() {
        return step;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setStep(String step) {
        this.step = step;
    }

    /** Not-null value. */
    public String getDayStep() {
        return dayStep;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDayStep(String dayStep) {
        this.dayStep = dayStep;
    }

    /** Not-null value. */
    public String getCalorie() {
        return calorie;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCalorie(String calorie) {
        this.calorie = calorie;
    }

    /** Not-null value. */
    public String getDistance() {
        return distance;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDistance(String distance) {
        this.distance = distance;
    }

    /** Not-null value. */
    public String getDayCalorie() {
        return dayCalorie;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDayCalorie(String dayCalorie) {
        this.dayCalorie = dayCalorie;
    }

    /** Not-null value. */
    public String getDayDistance() {
        return dayDistance;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setDayDistance(String dayDistance) {
        this.dayDistance = dayDistance;
    }

    /** Not-null value. */
    public String getData() {
        return data;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setData(String data) {
        this.data = data;
    }

	@Override
	public String toString() {
		return "RunData [id=" + id + ", mac=" + mac + ", mid=" + mid
				+ ", upload=" + upload + ", times=" + times + ", binTime="
				+ binTime + ", date=" + date + ", hour=" + hour + ", step="
				+ step + ", dayStep=" + dayStep + ", calorie=" + calorie
				+ ", distance=" + distance + ", dayCalorie=" + dayCalorie
				+ ", dayDistance=" + dayDistance + ", data=" + data + "]";
	}
    

}
