package com.szkct.weloopbtsmartdevice.data.greendao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table RUN.
 */
public class runshowdata {  // 我的页面 最佳的我，平均的我，上周的我 显示

   
    /** Not-null value. */
    private int best_step;
    /** Not-null value. */
    private String best_step_time;
    /** Not-null value. */
    private float best_dis;
    /** Not-null value. */
    private String best_dis_time;
    /** Not-null value. */
    private float best_kal;
    /** Not-null value. */
    private String best_kal_time;
    /** Not-null value. */
    private int average_step;
    /** Not-null value. */
    private int size;
    /** Not-null value. */
    private float average_dis;
    /** Not-null value. */
    private float average_kal;
    /** Not-null value. */
   
    private int week_step;
    private float week_dis;
    private float week_kal;

    public int getWeek_step() {
		return week_step;
	}



	public void setWeek_step(int week_step) {
		this.week_step = week_step;
	}



	public float getWeek_dis() {
		return week_dis;
	}



	public void setWeek_dis(float week_dis) {
		this.week_dis = week_dis;
	}



	public float getWeek_kal() {
		return week_kal;
	}



	public void setWeek_kal(float week_kal) {
		this.week_kal = week_kal;
	}



	public runshowdata() {
    }

   

    public runshowdata(int best_step, String best_step_time, float best_dis, String best_dis_time, float best_kal,
    		String best_kal_time, int average_step, float average_dis, float average_kal,int week_step,float week_dis,float week_kal, int size) {
        this.best_step = best_step;
        this.best_step_time = best_step_time;
        this.best_dis = best_dis;
        this.best_dis_time = best_dis_time;
        this.best_kal = best_kal;
        this.best_kal_time = best_kal_time;
        this.average_step = average_step;
        this.average_dis = average_dis;
        this.average_kal = average_kal;
        this.week_step = week_step;
        this.week_dis = week_dis;
        this.week_kal = week_kal;
        this.size = size;
        
    }





	public int getBest_step() {
		return best_step;
	}



	public void setBest_step(int best_step) {
		this.best_step = best_step;
	}



	public String getBest_step_time() {
		return best_step_time;
	}



	public void setBest_step_time(String best_step_time) {
		this.best_step_time = best_step_time;
	}



	public float getBest_dis() {
		return best_dis;
	}



	public void setBest_dis(float best_dis) {
		this.best_dis = best_dis;
	}



	public String getBest_dis_time() {
		return best_dis_time;
	}



	public void setBest_dis_time(String best_dis_time) {
		this.best_dis_time = best_dis_time;
	}



	public float getBest_kal() {
		return best_kal;
	}



	public void setBest_kal(float best_kal) {
		this.best_kal = best_kal;
	}



	public String getBest_kal_time() {
		return best_kal_time;
	}



	public void setBest_kal_time(String best_kal_time) {
		this.best_kal_time = best_kal_time;
	}



	public int getAverage_step() {
		return average_step;
	}



	public void setAverage_step(int average_step) {
		this.average_step = average_step;
	}



	public int getSize() {
		return size;
	}



	public void setSize(int size) {
		this.size = size;
	}



	public float getAverage_dis() {
		return average_dis;
	}



	public void setAverage_dis(float average_dis) {
		this.average_dis = average_dis;
	}



	public float getAverage_kal() {
		return average_kal;
	}



	public void setAverage_kal(float average_kal) {
		this.average_kal = average_kal;
	}




	
    

}
